resources:
- repo: self

phases:
#- phase: LinuxUbuntuTrusty
#  queue:
#    name: 'Hosted Linux Preview'
#  steps:
#  - task: Docker@0
#    displayName: Build
#    inputs:
#      containerregistrytype: 'Container Registry'
#      action: 'Run an image'
#      imageName: 'ethomson/libgit2-trusty:latest'
#      volumes: |
#       $(Build.SourcesDirectory):/src
#       $(Build.BinariesDirectory):/build
#      workDir: '/build'
#      containerCommand: '/src/script/cibuild.sh'
#      detached: false
#  - task: Docker@0
#    displayName: Test
#    inputs:
#      containerregistrytype: 'Container Registry'
#      action: 'Run an image'
#      imageName: 'ethomson/libgit2-trusty:latest'
#      volumes: |
#       $(Build.SourcesDirectory):/src
#       $(Build.BinariesDirectory):/build
#      workDir: '/build'
#      containerCommand: '/src/script/citest.sh'
#      detached: false
#
#- phase: macOS
#  queue:
#    name: 'Hosted macOS Preview'
#  steps:
#  - bash: . '$(Build.SourcesDirectory)/script/install-deps-osx.sh' '$(Build.BinariesDirectory)'
#    displayName: Install Dependencies
#  - bash: . '$(Build.SourcesDirectory)/script/cibuild.sh' '$(Build.BinariesDirectory)'
#    displayName: Build
#    env:
#      PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
#  - bash: . '$(Build.SourcesDirectory)/script/citest.sh' '$(Build.BinariesDirectory)'
#    displayName: Test
#    env:
#      TMPDIR: $(Agent.TempDirectory)

- phase: WindowsVisualStudioamd64
  queue:
    name: Hosted
  steps:
  - powershell: . '$(Build.SourcesDirectory)\script\cibuild.ps1' '$(Build.BinariesDirectory)'
    displayName: Build
    env:
      CMAKE_OPTIONS: -G"Visual Studio 12 2013 Win64"
  - powershell: . '$(Build.SourcesDirectory)\script\citest.ps1' '$(Build.BinariesDirectory)'
    displayName: Test

- phase: WindowsVisualStudiox86
  queue:
    name: Hosted
  steps:
  - powershell: . '$(Build.SourcesDirectory)\script\cibuild.ps1' '$(Build.BinariesDirectory)'
    displayName: Build
    env:
      CMAKE_OPTIONS: -G"Visual Studio 12 2013"
  - powershell: . '$(Build.SourcesDirectory)\script\citest.ps1' '$(Build.BinariesDirectory)'
    displayName: Test

- phase: WindowsMinGWamd64
  queue:
    name: Hosted
  steps:
  - task: automagically.DownloadFile.DownloadFile.DownloadFile@1
    displayName: Download MinGW
    inputs:
      FileUrl: 'https://bintray.com/libgit2/build-dependencies/download_file?file_path=mingw-w64-x86_64-8.1.0-release-win32-seh-rt_v6-rev0.zip'
      DestinationFolder: '$(Agent.TempDirectory)'
  - task: ExtractFiles@1
    displayName: Extract MinGW
    inputs:
      archiveFilePatterns: '$(Agent.TempDirectory)\mingw-w64-x86_64-8.1.0-release-win32-seh-rt_v6-rev0.zip'
      destinationFolder: '$(Agent.WorkFolder)'
      cleanDestinationFolder: false
  - powershell: . '$(Build.SourcesDirectory)\script\cibuild.ps1'
    displayName: Build
    env:
      CMAKE_OPTIONS: -G"MinGW Makefiles"
      PATH: $(Agent.WorkFolder)\mingw64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\CMake\bin
  - powershell: . '$(Build.SourcesDirectory)\script\citest.ps1' '$(Build.BinariesDirectory)'
    displayName: Test

- phase: WindowsMinGWx86
  queue:
    name: Hosted
  steps:
  - task: automagically.DownloadFile.DownloadFile.DownloadFile@1
    displayName: Download MinGW
    inputs:
      FileUrl: 'https://bintray.com/libgit2/build-dependencies/download_file?file_path=mingw-w64-i686-8.1.0-release-win32-sjlj-rt_v6-rev0.zip'
      DestinationFolder: '$(Agent.TempDirectory)'
  - task: ExtractFiles@1
    displayName: Extract MinGW
    inputs:
      archiveFilePatterns: '$(Agent.TempDirectory)\mingw-w64-i686-8.1.0-release-win32-sjlj-rt_v6-rev0.zip'
      destinationFolder: '$(Agent.WorkFolder)'
      cleanDestinationFolder: false
  - powershell: . '$(Build.SourcesDirectory)\script\cibuild.ps1'
    displayName: Build
    env:
      CMAKE_OPTIONS: -G"MinGW Makefiles"
      PATH: $(Agent.WorkFolder)\mingw32\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\CMake\bin
  - powershell: . '$(Build.SourcesDirectory)\script\citest.ps1' '$(Build.BinariesDirectory)'
    displayName: Test
